---
version: '3'
services:
  alertmanager:
    build: ./build/alertmanager
    image: planetary/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    env_file:
      - .env.alertmanager
    volumes:
      - ./configs/alertmanager/:/etc/alertmanager/
      - am_data:/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    healthcheck:
      test: wget --no-verbose --tries=1 http://alertmanager:9093/-/healthy
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.37.8
    restart: unless-stopped
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prom_data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    healthcheck:
      test: wget --no-verbose --tries=1 http://prometheus:9090/-/healthy
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:9.5.1
    restart: unless-stopped
    env_file:
      - .env.grafana
    volumes:
      - ./configs/grafana:/etc/grafana
      - gf_data:/var/lib/grafana
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://grafana:3000/api/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
volumes:
  prom_data:
  gf_data:
  am_data:
