global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - scheme: https
      static_configs:
      - targets: ["alertmanager:9093"]
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ["prometheus:9090"]
- job_name: node
  static_configs:
  - targets:
    - "rss.nos.social"
    - "notifications.nos.social:9100"
    - "dev-notifications.nos.social:9100"
    - "posthog.planetary.tools:9100"
    - "poetry.planetary.pub:9100"
    - "gardening.planetary.pub:9100"
    - "fungi.planetary.pub:9100"
    - "cooking.planetary.pub:9100"
    - "floss.planetary.pub:9100"
    - "crypto.planetary.pub:9100"
    - "queer.family:9100"
    - "espanol.planetary.pub:9100"
    - "russian-language.planetary.pub:9100"
    - "ukrainian-language.planetary.pub:9100"
    - "chinese-language.planetary.pub:9100"
    - "french-language.planetary.pub:9100"
    - "one.planetary.pub:9100"
    - "two.planetary.pub:9100"
    - "three.planetary.pub:9100"
    - "four.planetary.pub:9100"
- job_name: nos
  static_configs:
  - targets:
    - "events.nos.social:9100"
    - "tweeter.nos.social:9100"
    - "notifications.nos.social:9100"
    - "dev-notifications.nos.social:9100"
- job_name: posthog
  static_configs:
  - targets: ['posthog.planetary.tools:9100']
- job_name: pubs
  static_configs:
  - targets:
    - "poetry.planetary.pub:9100"
    - "gardening.planetary.pub:9100"
    - "fungi.planetary.pub:9100"
    - "cooking.planetary.pub:9100"
    - "floss.planetary.pub:9100"
    - "crypto.planetary.pub:9100"
    - "queer.family:9100"
    - "espanol.planetary.pub:9100"
    - "russian-language.planetary.pub:9100"
    - "ukrainian-language.planetary.pub:9100"
    - "chinese-language.planetary.pub:9100"
    - "french-language.planetary.pub:9100"
    - "one.planetary.pub:9100"
    - "two.planetary.pub:9100"
    - "three.planetary.pub:9100"
    - "four.planetary.pub:9100"
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets: ["posthog.planetary.tools:8080"]
- job_name: docker_stat_exporter
  scrape_interval: 5s
  static_configs:
  - targets: ["posthog.planetary.tools:2112"]
- job_name: nos_notification_service
  static_configs:
  - targets:
    - "notifications.nos.social"
    - "dev-notifications.nos.social"
- job_name: nos_crossposting_service
  static_configs:
  - targets:
    - "tweeter.nos.social"
- job_name: nos_event_service
  static_configs:
  - targets:
    - "events.nos.social"
- job_name: rsslay
  static_configs:
  - targets: ["rss.nos.social"]
