global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - scheme: https
      static_configs:
      - targets: ["alertmanager:9093"]
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ["prometheus:9090"]
- job_name: posthog
  static_configs:
  - targets: ['posthog.planetary.tools:9100']
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets: ["posthog.planetary.tools:8080"]
- job_name: docker_stat_exporter
  scrape_interval: 5s
  static_configs:
  - targets: ["posthog.planetary.tools:2112"]
